package com.lyx.examsystem.entity;

public class TopicInfoEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.Title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.OptionA
     *
     * @mbggenerated
     */
    private String optiona;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.OptionB
     *
     * @mbggenerated
     */
    private String optionb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.OptionC
     *
     * @mbggenerated
     */
    private String optionc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.OptionD
     *
     * @mbggenerated
     */
    private String optiond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.OptionE
     *
     * @mbggenerated
     */
    private String optione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.OptionF
     *
     * @mbggenerated
     */
    private String optionf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.Result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TopicInfo.Complexity
     *
     * @mbggenerated
     */
    private String complexity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.ID
     *
     * @return the value of TopicInfo.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.ID
     *
     * @param id the value for TopicInfo.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.Type
     *
     * @return the value of TopicInfo.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.Type
     *
     * @param type the value for TopicInfo.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.Title
     *
     * @return the value of TopicInfo.Title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.Title
     *
     * @param title the value for TopicInfo.Title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.OptionA
     *
     * @return the value of TopicInfo.OptionA
     *
     * @mbggenerated
     */
    public String getOptiona() {
        return optiona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.OptionA
     *
     * @param optiona the value for TopicInfo.OptionA
     *
     * @mbggenerated
     */
    public void setOptiona(String optiona) {
        this.optiona = optiona == null ? null : optiona.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.OptionB
     *
     * @return the value of TopicInfo.OptionB
     *
     * @mbggenerated
     */
    public String getOptionb() {
        return optionb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.OptionB
     *
     * @param optionb the value for TopicInfo.OptionB
     *
     * @mbggenerated
     */
    public void setOptionb(String optionb) {
        this.optionb = optionb == null ? null : optionb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.OptionC
     *
     * @return the value of TopicInfo.OptionC
     *
     * @mbggenerated
     */
    public String getOptionc() {
        return optionc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.OptionC
     *
     * @param optionc the value for TopicInfo.OptionC
     *
     * @mbggenerated
     */
    public void setOptionc(String optionc) {
        this.optionc = optionc == null ? null : optionc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.OptionD
     *
     * @return the value of TopicInfo.OptionD
     *
     * @mbggenerated
     */
    public String getOptiond() {
        return optiond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.OptionD
     *
     * @param optiond the value for TopicInfo.OptionD
     *
     * @mbggenerated
     */
    public void setOptiond(String optiond) {
        this.optiond = optiond == null ? null : optiond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.OptionE
     *
     * @return the value of TopicInfo.OptionE
     *
     * @mbggenerated
     */
    public String getOptione() {
        return optione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.OptionE
     *
     * @param optione the value for TopicInfo.OptionE
     *
     * @mbggenerated
     */
    public void setOptione(String optione) {
        this.optione = optione == null ? null : optione.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.OptionF
     *
     * @return the value of TopicInfo.OptionF
     *
     * @mbggenerated
     */
    public String getOptionf() {
        return optionf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.OptionF
     *
     * @param optionf the value for TopicInfo.OptionF
     *
     * @mbggenerated
     */
    public void setOptionf(String optionf) {
        this.optionf = optionf == null ? null : optionf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.Result
     *
     * @return the value of TopicInfo.Result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.Result
     *
     * @param result the value for TopicInfo.Result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TopicInfo.Complexity
     *
     * @return the value of TopicInfo.Complexity
     *
     * @mbggenerated
     */
    public String getComplexity() {
        return complexity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TopicInfo.Complexity
     *
     * @param complexity the value for TopicInfo.Complexity
     *
     * @mbggenerated
     */
    public void setComplexity(String complexity) {
        this.complexity = complexity == null ? null : complexity.trim();
    }
}