package com.lyx.examsystem.dao;

import com.lyx.base.page.Page;
import com.lyx.examsystem.entity.TopicInfoEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TopicInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TopicInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TopicInfo
     *
     * @mbggenerated
     */
    int insert(TopicInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TopicInfo
     *
     * @mbggenerated
     */
    int insertSelective(TopicInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TopicInfo
     *
     * @mbggenerated
     */
    TopicInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TopicInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TopicInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TopicInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TopicInfoEntity record);

    List<TopicInfoEntity> selectPageByContent(Page page);

    //提前定义Content,以免xml里报错
    int selectCountByContent(@Param(value = "content") String Content);

    int deleteByIds(@Param(value = "ids")String ids);

    List<TopicInfoEntity> selectListByRandom();

}